##########
# By: Ethan Gyllenhaal
# Updated 28Feb2024
#
# R script used for generating manhattan plots.
# First sets up function (modified version of one the authors of qqman suggest).
# Then has calls of that function for given input files generated by vcftools and a renaming script.
# Note that chromosomes will be numbered 1-N, but that may not correspond to chromosome names.
## e.g., here 1-3 are 1, 1A, and 1B.
#########

#install.packages("qqman", dep=T)
library(qqman)
setwd('/path/to/directory')

# plotting function
plot_fst <- function(input, title_name){
  fst <- read.table(input, header=TRUE)
  fstsubset <- fst[complete.cases(fst),]
  SNP<-c(1:(nrow(fstsubset)))
  snp_df<-data.frame(SNP,fstsubset)
  manhattan(snp_df,chr="CHROM",bp="BIN_START",p="WEIGHTED_FST",snp="SNP",logp=FALSE, ylab="Weir and Cockerham Fst", main=title_name, cex=1.5)
}


# Geography ones, 3 used in Fig 4, others in S5
par(mfrow=c(3,3), mar=c(2,1,2,1), oma=c(0,2,0,0))

plot_fst("vanuaW_vanuaE_weir_10k.fst", "Vanua W-E")
plot_fst("vanuaW_vanuaC_weir_10k.fst", "Vanua W-C")
plot_fst("vanuaC_vanuaE_weir_10k.fst", "Vanua C-E")
plot_fst("vanuaE_rabi_weir_10k.fst", "VanuaE-Rabi")
plot_fst("vanuaW_rabi_weir_10k.fst", "VanuaW-Rabi")
plot_fst("taveuni_rabi_weir_10k.fst", "Taveuni-Rabi")
plot_fst("vanuaE_kioa_weir_10k.fst", "VanuaE-Kioa")
plot_fst("vanuaW_kioa_weir_10k.fst", "VanuaW-Kioa")
plot_fst("viti_ovalau_weir_10k.fst", "Viti-Ovalau")

# Phenotype, used in Fig 4
par(mfrow=c(3,1), mar=c(2,1,2,1), oma=c(0,2,0,0))

# Band
plot_fst("band01_band23_weir_10k.fst", "Band 01-23")
# Lores
plot_fst("lores0_lores12_weir_10k.fst", "Lores 0-12")
# Index
plot_fst("index01_index345_weir_10k.fst", "Index 01-345")